---

- name: install builder
  hosts: local
  become: yes
  gather_facts: False

  tasks:
  - name: Create a keypair
    ec2_key:
      name: newkey1
      state: absent
    #register: ec2_key_result

  - name: Save
    copy:
      content: "{{ ec2_key_result.key.private_key }}"
      dest: ~/.ssh/newkey1.pem
      mode: 0600
    when: ec2_key_result.changed

