---

- name: install builder
  hosts: local
  become: yes
  gather_facts: False

  tasks:

  - name: Create a keypair
    ec2_key:
      name: newkey1
      #state: absent
    register: ec2_key_result

  - name: Save
    copy:
      content: "{{ ec2_key_result.key.private_key }}"
      dest: ~/.ssh/newkey1.pem
      mode: 0600
    when: ec2_key_result.changed

  - name: Create new security group
    ec2_group:
      name: group1
      description: AWS_APP group
      region: eu-north-1
      rules:
        - proto: tcp
          ports:
            - 0-65535
          cidr_ip: 0.0.0.0/0


