---

- name: install builder
  hosts: localhost
  become: yes
  gather_facts: False

  tasks:
  - name: Create a keypair
    ec2_key:
      name: newkey1

  - name: Save private key
    copy: content="{{ ec2_key_result.key.private_key }}" dest="~/.ssh/newket1.pem" mode=400
    when: ec2_key_result.changed
